### ISSUE TITLE
implement initial auth feature

### ISSUE THREAD

**Issue by diegofigs** [THSUPRM/ths-client#8]
- should include Auth Controller for validating and verifying inputs
- should include Auth Service for sharing business logic
- should be encapsulated in its own module and folder
- all files should be encapsulated in IIFE's (Initially Invoked Function Expressions)

Tasks:
- [x] #14: auth.module.js
- [x] #15: auth.controller.js
- [x] #16: auth.service.js
