### ISSUE TITLE
implement initial tweet feature

### ISSUE THREAD

**Issue by diegofigs** [THSUPRM/ths-client#9]
- should include Tweet Controller for validating and verifying inputs
- should include Tweet Service for sharing business logic
- should be encapsulated in its own module and folder i.e.
- all files should be encapsulated in IIFE's (Initially Invoked Function Expressions)

Tasks:
- [x] #11 tweets.module.js
- [x] #12 tweets.controller.js
- [x] #13 tweets.service.js
